kamel:
  install:
    olm: false
    maven-repositories: 'http://nexus.fuse-qe.eng.rdu2.redhat.com/repository/fuse7-all/'
    base-image: 'registry-proxy.engineering.redhat.com/rh-osbs/fuse7-fuse-java-openshift:fuse-8.0-openshift-rhel-8-containers-candidate-12026-20200331140212'
    operator-image: 'quay.io/rh_integration/camel-k:fuse-8.0-openshift-rhel-8-containers-candidate-76998-20200403150707'
  run:
    integration:
      crime-bridge:
        property-files: '[config/application.properties]'
        dependencies: '[mvn:org.apache.activemq:artemis-jms-client:2.11.0.redhat-00005]'
      earthquake-bridge:
        property-files: '[config/application.properties]'
        dependencies: '[mvn:org.apache.activemq:artemis-jms-client:2.11.0.redhat-00005]'
      earthquake-consumer:
        property-files: '[config/application.properties]'
      health-bridge:
        property-files: '[config/application.properties]'
        dependencies: '[mvn:org.apache.activemq:artemis-jms-client:2.11.0.redhat-00005]'
      open-aq-consumer:
        property-files: '[config/application.properties]'
      pollution-bridge:
        property-files: '[config/application.properties]'
        dependencies: '[mvn:org.apache.qpid:qpid-jms-client:0.45.0.redhat-00002]'
      timeline-bridge:
        property-files: '[config/application.properties]'
        dependencies: '[camel-jackson,camel-direct,camel-rest,camel-netty-http]'
      user-report-system:
        dependencies: '[camel-netty-http]'
        secrets: '[example-event-streaming-user-reporting]'
